"""empty message

Revision ID: 944b5d7fef33
Revises: 
Create Date: 2023-05-11 14:41:44.144299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944b5d7fef33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('stu_id', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stu_id')
    )
    op.create_table('videouri',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_title', sa.Text(), nullable=False),
    sa.Column('video_label', sa.Text(), nullable=False),
    sa.Column('video_uri', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videouri.id'], ),
    sa.PrimaryKeyConstraint('favorite_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('videouri')
    op.drop_table('user')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
